[package]
authors.workspace = true
categories.workspace = true
description = "moshpits server (mps) — server daemon for moshpit remote terminal sessions"
documentation = "https://github.com/rustyhorde/moshpit#moshpits-server-mps"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "moshpits"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "mps"
path = "src/main.rs"

[features]
unstable = ["libmoshpit/unstable"]

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
getset = { workspace = true }
libmoshpit = { workspace = true }
portable-pty = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["signal", "sync", "time"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber-init = { workspace = true }
uuid = { workspace = true }
vergen-pretty = { workspace = true }
vt100 = { workspace = true }
zstd = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
zbus = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "test-util"] }

[build-dependencies]
anyhow = { workspace = true }
rustversion = { workspace = true }
vergen-gix = { workspace = true }
