[package]
authors.workspace = true
categories.workspace = true
description = "Perform various key tasks for moshpit"
documentation = "https://github.com/rustyhorde/moshpit#mp-keygen"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "moshpit-keygen"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "mp-keygen"
path = "src/main.rs"

[features]
unstable = ["libmoshpit/unstable"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
dialoguer = { workspace = true }
getset = { workspace = true }
libmoshpit = { workspace = true }
vergen-pretty = { workspace = true }
[build-dependencies]
anyhow = { workspace = true }
rustversion = { workspace = true }
vergen-gix = { workspace = true }
