[package]
authors.workspace = true
categories.workspace = true
description = "A Rust implementation of in the same vein as Mosh, the mobile shell."
documentation = "https://docs.rs/libmoshpit"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "libmoshpit"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
unstable = ["aws-lc-rs/unstable"]

[dependencies]
ansi-control-codes = { workspace = true }
anyhow = { workspace = true }
argon2 = { workspace = true }
aws-lc-rs = { workspace = true }
base64 = { workspace = true }
bincode-next = { workspace = true }
bishop = { workspace = true }
bon = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
dirs2 = { workspace = true }
getset = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
socket2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["process", "sync", "time"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-subscriber-init = { workspace = true }
uuid = { workspace = true }
vt100 = { workspace = true }
whoami = { workspace = true }
zeroize = { workspace = true }
zstd = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
rustversion = { workspace = true }
vergen-gix = { workspace = true }

[dev-dependencies]
bincode-next = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "net",
    "rt-multi-thread",
    "time",
] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
