max_reconnect_backoff_secs = 3600   # 1 hour

[mps]
ip = "127.0.0.1"
port = 40406

[tracing.file]
quiet = 0
verbose = 3

[tracing.file.layer]
with_target = true
with_thread_ids = false
with_thread_names = false
with_line_number = true
with_level = true
directives = "mio=error,neli=error"
