[package]
authors.workspace = true
categories.workspace = true
description = "moshpit client (mp) — encrypted, resilient remote terminal session client"
documentation = "https://github.com/rustyhorde/moshpit#moshpit-client-mp"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "moshpit"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "mp"
path = "src/main.rs"

[features]
unstable = ["libmoshpit/unstable"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
crossterm = { workspace = true }
dialoguer = { workspace = true }
dirs2 = { workspace = true }
getset = { workspace = true }
libmoshpit = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
terminal_size = { workspace = true }
tokio = { workspace = true, features = ["io-std", "signal", "sync", "time"] }
tokio-util = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
vergen-pretty = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
rustversion = { workspace = true }
vergen-gix = { workspace = true }
