on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "27 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 🦀 moshpit 🦀

jobs:
  rustfmt:
    name: 📌 Formatting 📌
    # main
    uses: rustyhorde/workflows/.github/workflows/rustfmt.yml@6be19e3927788d11edc91039775572b132b38fe4

  lints-linux:
    name: 🕳️ Clippy (Linux) 🕳️
    needs: rustfmt
    # main
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@6be19e3927788d11edc91039775572b132b38fe4
    with:
      os: ubuntu-latest
      channel: nightly
      target: x86_64-unknown-linux-gnu

  lints-macos:
    name: 🕳️ Clippy (MacOS) 🕳️
    needs: rustfmt
    # main
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@6be19e3927788d11edc91039775572b132b38fe4
    with:
      os: macos-latest
      channel: nightly
      target: apple-darwin

  lints-windows:
    name: 🕳️ Clippy (Windows) 🕳️
    needs: rustfmt
    # main
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@6be19e3927788d11edc91039775572b132b38fe4
    with:
      os: windows-latest
      channel: nightly
      target: x86_64-pc-windows-gnu

  test-linux:
    name: 🧪 Test (Linux) 🧪
    needs: lints-linux
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: ["1.91.1", "stable", "beta", "nightly"]
        target: [x86_64-unknown-linux-gnu]
    # main
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@6be19e3927788d11edc91039775572b132b38fe4
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}

  test-macos:
    name: 🧪 Test (MacOS) 🧪
    needs: lints-macos
    strategy:
      matrix:
        os: [macos-latest]
        channel: ["1.91.1", "stable", "beta", "nightly"]
        target: [apple-darwin]
    # main
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@6be19e3927788d11edc91039775572b132b38fe4
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}

  test-windows:
    name: 🧪 Test (Windows) 🧪
    needs: lints-windows
    strategy:
      matrix:
        os: [windows-latest]
        channel: ["1.91.1", "stable", "beta", "nightly"]
        target: [x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]
    # main
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@6be19e3927788d11edc91039775572b132b38fe4
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}

  coverage-linux:
    name: 🧱 Coverage (Linux) 🧱
    needs: test-linux
    # main
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@6be19e3927788d11edc91039775572b132b38fe4
    with:
      os: ubuntu-latest
      channel: nightly
      target: x86_64-unknown-linux-gnu
      lcov: true
      html: true
      run_cmd: ${{ vars.COVERAGE_RUN_CMD }}
    secrets: inherit

  coverage-macos:
    name: 🧱 Coverage (MacOS) 🧱
    needs: test-macos
    # main
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@6be19e3927788d11edc91039775572b132b38fe4
    with:
      os: macos-latest
      channel: nightly
      target: apple-darwin
      lcov: true
      html: true
      run_cmd: ${{ vars.COVERAGE_RUN_CMD }}
    secrets: inherit

  coverage-windows:
    name: 🧱 Coverage (Wndows) 🧱
    needs: test-windows
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]
    # main
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@6be19e3927788d11edc91039775572b132b38fe4
    with:
      os: windows-latest
      channel: nightly
      target: ${{ matrix.target }}
      lcov: true
      html: true
      run_cmd: ${{ vars.COVERAGE_RUN_CMD }}
    secrets: inherit